travis:
  secure:
    BINSTAR_TOKEN: F7iGkeYmdyHYD99PZziwbkbukIw+1YfhSMnAzaJAr2INWgbie/ggeIO3zTcu7WQXPcSkQLhlu72kddvShTSklTjJhRgblYHU2uykWkayW6HM5i3tJwu6e2Xeep/fIUjCN+6+J9n6l65GiWfh2hvBTSyzu2voRfKpjlYtR0q0ep1GFuf2APwpYct28Ow8x2jIcjQDwaSP3okEb1e2Xkl9m8KDH7oaiumI+2f5T13XrHCaBEhFJrVRQsYPILJqCDYNHmRKI4Gqm/9aA+yceORpX/wf/7dFf0Vubk0RwFiER+t8jNE1Y8lXa+BHxh1Xg4BGYcy9/QAwrhHxiW3NnfMZuP264EkjRo5xXPwslCdyXo6XV0LuaMIRAalGyWt2/VToW3ppMD2wLq30MBw3BOMGOnl8EdvdrfsNSywVAFjxht82vFLctlA0d85bOp++qNnGKh1mRryh3TroYfmSiP0/SBXlEVZInFSI0w2/qOlm04jXRGZ8aUg0Pjm5zSpeK912uemdd2Hqs7oVNEdNGxMIHVGLZGnDwem0JlNJYAsF3e6kJVvUYEs/7knS7NU1XT4pcGdnkY/+NOItaYQqDpeJmUCJfofjwEkHszWUBzHsbJNOPEJn8lEjQWs/YZPqO4wNWTUmyYfoqnA3nPkVI8hxlttK4kVHDuUh2FE5gVK0h2Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
